services:
  postgres:
    image: postgres:16-alpine
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_DB: "nestjs_demo"
      POSTGRES_USER: "nestjs_user"
      POSTGRES_PASSWORD: "nestjs_pass"
    ports:
      - "35432:5432"
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data
    shm_size: 128mb
